
<?php echo $this->getContent(); ?>

<div align="center">
   <h1>Edit user</h1>
</div>
<div class="alert alert-success" id="user-details"></div>

<div class="tab-pane" id="edit">
   <br/>
   <br/>
   <?php echo $this->tag->form(array('id' => 'editForm', 'role' => 'form')) ?>
   <div class="form-group">
      <label for="username">Username</label>
      <?php echo $this->tag->textField(array("username", "size" => 30, 'class' => 'form-control', 'id' => 'username')) ?>
   </div>
   <div class="form-group">
      <label for="email">Email</label>
      <?php echo $this->tag->textField(array("email", "size" => 30, 'class' => 'form-control', 'id' => 'email')) ?>

   </div>
   <div class="form-group">
      <label for="password">Password</label>
      <?php echo $this->tag->textField(array("password", "size" => 30, 'class' => 'form-control', 'id' => 'password')) ?>  
   </div>
   <td class="btn-group">
      <?php echo $this->tag->hiddenField(array("id")) ?>
      <?php echo $this->tag->submitButton(array("Save", 'class' => 'btn btn-success')) ?>
      <?php echo $this->tag->linkTo(array("user/index", "Go Back", 'class' => 'btn')) ?>
   </td>
</form>
<br/>
</div>
<script type="text/javascript">
  $('#editForm').submit(updateUser);
</script>
